
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/Bibekananda-PC/miniconda3/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.19.0-50-generic - x86_64
...
